openapi: 3.0.3
info: { title: FiscalManager Total API, version: 1.0.0 }
servers: [ { url: https://fiscalmanager-backend.onrender.com/api } ]
paths:
  /health:
    get: { summary: Health, responses: { '200': { description: OK } } }
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: { email: {type: string}, senha: {type: string} }
      responses: { '200': { description: Tokens } }
  /empresas:
    get: { summary: Listar, responses: { '200': { description: OK } } }
    post: { summary: Criar, responses: { '201': { description: Created } } }
  /produtos:
    get: { summary: Listar, responses: { '200': { description: OK } } }
    post: { summary: Criar, responses: { '201': { description: Created } } }
  /notas:
    get: { summary: Listar, responses: { '200': { description: OK } } }
  /notas/import-xml:
    post: { summary: Importar XML, responses: { '201': { description: Created } } }
